dist: trusty
language: node_js
node_js:
  - '12'
cache:
  npm: false
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database "pothos-test";' -U postgres
script:
  - npm run test
